import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdir } from 'node:fs/promises';
import { chromium, expect } from '@playwright/test';
import { createServer } from 'vite';
import { createGameServer } from '../../server/andin/server.js';
import { MemoryStore } from '../../server/andin/storage.js';
import { MAPS } from '../../shared/andin/world.js';

test('desktop and mobile: lobby, 3D, farming, sitting, sleeping, economy and four maps', { timeout: 300000 }, async (t) => {
  const errors = [];
  const origins = [];
  const game = await createGameServer({ store: new MemoryStore(), origins, verifyToken: async (token) => {
    const [prefix, uid, name] = token.split(':');
    if (prefix !== 'dev') throw new Error('Invalid test identity');
    return { uid, name };
  } });
  game.server.listen(0, '127.0.0.1');
  await once(game.server, 'listening');
  const vite = await createServer({
    logLevel: 'error',
    cacheDir: '.andin-test-artifacts/vite-cache',
    server: { host: '127.0.0.1', port: 0, strictPort: false },
    define: { 'import.meta.env.VITE_ANDIN_WS_URL': JSON.stringify(`ws://127.0.0.1:${game.server.address().port}/api/andin/ws`) },
  });
  await vite.listen();
  const origin = `http://127.0.0.1:${vite.httpServer.address().port}`;
  origins.push(origin);
  const browser = await chromium.launch({ headless: true, args: ['--enable-unsafe-swiftshader'] });
  let page;
  let completed = false;
  t.after(async () => {
    if (!completed && page) t.diagnostic((await page.locator('body').innerText({ timeout: 2000 }).catch(() => 'Page unresponsive')).slice(-5000));
    await browser.close();
    await vite.close();
    await game.close();
  });
  await mkdir('.andin-test-artifacts', { recursive: true });
  const context = await browser.newContext({ viewport: { width: 1280, height: 720 } });
  page = await context.newPage();
  page.setDefaultTimeout(30000);
  page.setDefaultNavigationTimeout(60000);
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(`${origin}/andin-preview`, { waitUntil: 'domcontentloaded' });
  await page.getByLabel('Nama pemain pengujian').fill('Anas');
  await page.getByRole('button', { name: 'Mulai pengujian' }).click();
  await expect(page.getByText('Server terhubung')).toBeVisible({ timeout: 20000 });
  await page.screenshot({ path: '.andin-test-artifacts/lobby-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Buat kebun baru' }).click();
  await expect(page.getByRole('heading', { name: 'Pilih karaktermu' })).toBeVisible();
  await page.getByRole('button', { name: /Bapak/ }).click();
  await page.getByRole('button', { name: 'Masuk ke kebun' }).click();
  await expect(page.locator('.andin-game canvas')).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('heading', { name: 'Grafis 3D tidak dapat dimuat' })).not.toBeVisible();
  assert.equal(await page.locator('.andin-game canvas').evaluate((canvas) => {
    const gl = canvas.getContext('webgl2');
    return Boolean(gl && !gl.isContextLost());
  }), true, 'A live WebGL2 context renders the game');
  await expect(page.getByText('Pemain Online: 1/5')).toBeVisible();
  await page.waitForTimeout(1800);
  await page.screenshot({ path: '.andin-test-artifacts/home-desktop.png' });
  await page.getByRole('button', { name: 'Pengaturan', exact: true }).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Tutup dialog' }).click();
  const entry = [...game.rooms.values()][0];
  const uid = Object.keys(entry.room.data.players)[0];
  const player = entry.room.data.players[uid];
  const near = async (object, mapId = 'home') => {
    Object.assign(player, { x: object.x, z: object.z + (object.mapId ? 0.45 : 1.8), mapId, pose: 'idle' });
    const label = object.to ? 'Pergi' : { chair: 'Duduk', bed: 'Tidur', shop: 'Beli benih', bin: 'Jual panen' }[object.type] || 'Periksa';
    await expect(page.locator('.andin-location strong')).toHaveText(MAPS[mapId].name, { timeout: 20000 });
    await expect(page.locator('.andin-interact')).toContainText(label, { timeout: 20000 });
  };
  const startX = player.x;
  await page.keyboard.down('d');
  await page.waitForTimeout(1000);
  await expect.poll(() => player.x, { timeout: 8000, message: 'WASD moves the authoritative player' }).toBeGreaterThan(startX);
  await page.keyboard.up('d');
  await expect.poll(() => entry.room.sessions.get(uid).input.x).toBe(0);
  const plot = MAPS.home.plots[0];
  await near(plot);
  await page.getByTitle('Cangkul (2)', { exact: true }).click();
  await page.keyboard.press('e');
  await expect.poll(() => entry.room.data.plots[plot.id]?.tilled).toBe(true);
  await page.getByTitle('Benih (4)', { exact: true }).click();
  await page.keyboard.press('e');
  await expect.poll(() => entry.room.data.plots[plot.id]?.crop).toBe('turnip');
  await page.getByTitle('Penyiram (3)', { exact: true }).click();
  await page.keyboard.press('e');
  await expect.poll(() => entry.room.data.plots[plot.id]?.wateredDay).toBe(0);
  console.log('Browser: farming actions verified');
  await page.screenshot({ path: '.andin-test-artifacts/farming-desktop.png' });
  await near(MAPS.home.house.chairs[0]);
  console.log('Browser: approaching chair');
  await expect(page.locator('.andin-interact')).toContainText('Duduk');
  await page.locator('.andin-interact').click();
  await expect.poll(() => player.pose).toBe('sit');
  console.log('Browser: sitting verified');
  await page.waitForTimeout(500);
  await page.screenshot({ path: '.andin-test-artifacts/sitting-desktop.png' });
  await page.getByRole('button', { name: 'Berdiri / bangun' }).click();
  await expect.poll(() => player.pose).toBe('idle');
  entry.room.join({ uid: 'sleep-observer', name: 'Pengamat Tidur' }, 'anak', 'observer-session');
  await near(MAPS.home.house.beds[0]);
  await page.locator('.andin-interact').click();
  await page.getByRole('button', { name: 'Tidur sampai besok' }).click();
  await expect.poll(() => player.pose).toBe('sleep');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.waitForTimeout(500);
  await page.screenshot({ path: '.andin-test-artifacts/sleeping-desktop.png' });
  entry.room.disconnect('sleep-observer', 'observer-session', Date.now(), true);
  await expect.poll(() => entry.room.data.day).toBe(1);
  assert.equal(entry.room.data.plots[plot.id].growth, 1);
  await near(MAPS.home.props[1]);
  await page.locator('.andin-interact').click();
  const gold = entry.room.data.gold;
  await page.getByRole('button', { name: 'Beli 1 · 10 G', exact: true }).click();
  await expect.poll(() => entry.room.data.gold).toBe(gold - 10);
  await page.getByRole('button', { name: 'Tutup dialog' }).click();
  console.log('Browser: sleep and seed purchases verified');
  for (const portal of MAPS.home.portals) {
    await near(portal);
    await page.locator('.andin-interact').click();
    await page.getByRole('button', { name: 'Mulai perjalanan' }).click();
    await expect.poll(() => player.mapId).toBe(portal.to);
    console.log(`Browser: travel to ${portal.to} verified`);
    await page.waitForTimeout(600);
    await page.screenshot({ path: `.andin-test-artifacts/map-${portal.to}.png` });
  }
  await page.getByRole('button', { name: 'Peta perjalanan', exact: true }).click();
  console.log('Browser: desktop rendering paused before mobile verification');
  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const mobile = await mobileContext.newPage();
  mobile.on('pageerror', (error) => errors.push(error.message));
  await mobile.goto(`${origin}/andin-preview`, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await mobile.getByLabel('Nama pemain pengujian').fill('Andin');
  await mobile.getByRole('button', { name: 'Mulai pengujian' }).click();
  await expect(mobile.getByText('Server terhubung')).toBeVisible();
  console.log('Browser: mobile lobby connected');
  await mobile.getByLabel('Kode undangan').fill(entry.room.data.code);
  await mobile.getByRole('button', { name: 'Gabung', exact: true }).click();
  await mobile.getByRole('button', { name: /Ibuk/ }).click();
  await mobile.getByRole('button', { name: 'Masuk ke kebun' }).click();
  await expect(mobile.getByText('Pemain Online: 2/5')).toBeVisible();
  console.log('Browser: second player joined from mobile');
  await expect(page.getByText('Pemain Online: 2/5')).toBeVisible();
  const oldSession = entry.room.sessions.get(uid).sessionId;
  [...entry.clients].find((client) => client.identity.uid === uid).close(1012, 'Test reconnect');
  await expect.poll(() => entry.room.sessions.get(uid)?.sessionId, { timeout: 20000 }).not.toBe(oldSession);
  await expect(page.getByText('Pemain Online: 2/5')).toBeVisible();
  await expect(mobile.locator('.andin-game canvas')).toBeVisible();
  await mobile.waitForTimeout(800);
  await mobile.screenshot({ path: '.andin-test-artifacts/home-mobile.png' });
  assert.equal(await mobile.evaluate(() => document.querySelector('.andin-app').scrollWidth <= window.innerWidth), true, 'No horizontal overflow on mobile');
  await mobile.getByRole('button', { name: 'Peta perjalanan', exact: true }).click();
  await expect(mobile.getByRole('dialog')).toBeVisible();
  await mobile.screenshot({ path: '.andin-test-artifacts/map-mobile.png' });
  await mobile.getByRole('button', { name: 'Tutup dialog' }).click();
  await mobile.getByRole('button', { name: 'Kembali ke lobby', exact: true }).click();
  await mobile.getByRole('dialog').getByRole('button', { name: 'Kembali ke lobby' }).click();
  await expect(mobile.getByRole('heading', { name: 'Mau ke kebun mana?' })).toBeVisible();
  await expect(page.getByText('Pemain Online: 1/5')).toBeVisible();
  assert.deepEqual(errors, []);
  completed = true;
});
